home 3 add
whiskas90/HomeWorkAndroid pull request #3
Opened 2019-10-05 19:44 UTC by whiskas90

home 3 done

2019-10-08 19:48 UTC, NailShaykhrazievItis requested changes

2019-10-08 19:48 UTC, NailShaykhrazievItis commented on app/build.gradle
> +    //implementation 'com.android.support:appcompat-v7:29.+'
Это можешь удалить

2019-10-08 19:48 UTC, NailShaykhrazievItis commented on app/build.gradle
> +    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
лучше jdk8

2019-10-08 19:48 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/myandroidproject/ChangePasswordActivity.kt
> +        val backButton:Button = findViewById(R.id.backButton)
Можешь удалить эту строку и ничего не измениться. У тебя id автоматически подтянется

2019-10-08 19:48 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/myandroidproject/LoginActivity.kt
> +                progressBar.visibility = View.VISIBLE
Можно было View.Visible вынести за if. И вызвать 2 раза, а не 4 =)

2019-10-08 19:48 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/myandroidproject/LoginActivity.kt
> +    object passwordRepository {
Лучше в отдельный файл бы вынести

2019-10-08 19:48 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/myandroidproject/MainActivity.kt
> +        //
Удалить

2019-10-08 19:48 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/activity_change_password.xml
> +
Лишняя строка.

2019-10-08 21:26 UTC, whiskas90 commented
Исправил

2019-10-10 21:01 UTC, NailShaykhrazievItis approved these changes

2019-10-11 05:33 UTC, closed without merging