Task/home5
whiskas90/HomeWorkAndroid pull request #5
Opened 2019-10-31 19:53 UTC by whiskas90

hw 5 done

2019-11-03 09:52 UTC, whiskas90 commented
![photo_2019-11-03_11-51-22](https://user-images.githubusercontent.com/42836742/68082659-75d09500-fe30-11e9-9bba-4cde952efcf9.jpg)
![photo_2019-11-03_11-51-22 (2)](https://user-images.githubusercontent.com/42836742/68082660-75d09500-fe30-11e9-9776-45433d47ec4f.jpg)

2019-11-12 12:06 UTC, NailShaykhrazievItis requested changes

2019-11-12 12:06 UTC, NailShaykhrazievItis commented on app/build.gradle
> +    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
Смержи изменения в этом файле в мастер чтоб каждый раз не писать. Можешь отдельной веткой, можешь сразу в мастер коммит сделать

2019-11-12 12:06 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/myandroidproject/MainActivity.kt
> +        button_go_activity_navigation.setOnClickListener {
Тут какая то старая домашка. Создавайте новые ветки от мастера. В следующий раз -1 балл

2019-11-12 12:06 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/mydzfive/CitiesClass.kt
> +class CitiesClass(var name: String, var img: Int, val description: String) {
data class CitiesClass(var name: String, var img: Int, val description: String)

{} не нужны

2019-11-12 12:06 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/mydzfive/MyRecycler.kt
> +class MyRecycler : AppCompatActivity() {
MyRecyclerActivity

2019-11-12 12:06 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/mydzfive/adapter/MyRecyclerAdapter.kt
> +    class ViewHolder(itemView: View?) : RecyclerView.ViewHolder(itemView!!) {
!! -1 балл
implement LayoutContainer 
https://kotlinlang.org/docs/tutorials/android-plugin.html#layoutcontainer-support

Вынести в отдельный класс

2019-11-12 12:06 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/mydzfive/adapter/MyRecyclerAdapter.kt
> +        val itemView =
Не ответсвенность адаптера значть из какого xml файла рисуются его итемы. Вынести в холдер создание элемента списка

2019-11-12 12:06 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/mydzfive/adapter/MyRecyclerAdapter.kt
> +        holder?.textView?.text = values[position].name
Не ответственность адаптера знать какие элементы лежат внутри его холдера. Он должен передать class в холдер и холдер будет решать что из этих данных должны куда сетиться.

2019-11-12 12:06 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/mydzfive/adapter/MyRecyclerAdapter.kt
> +        holder.itemView.setOnClickListener { v ->
Адаптер не знает о сущнсоти активити и что там как то экраны могут менятся. Не его это ответсвенность. За навигацию отвечает активити. Вынести в лямбду

Пример: https://github.com/NailShaykhrazievItis/Template/tree/task/rekyklep/app

2019-11-12 12:06 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/mydzfive/adapter/MyRecyclerAdapter.kt
> +}
add line after class

2019-11-12 12:06 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/activity_detail.xml
> +
extra line

2019-11-12 12:06 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/activity_detail.xml
> +
extra line

2019-11-12 12:06 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/activity_detail.xml
> +        app:layout_constraintHorizontal_bias="0.5"
значение по умолчанию, нет смысла писать

2019-11-12 12:06 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/activity_detail.xml
> +        android:maxHeight="50dp"
Ну сойдет, единственное все числовые значения в андроиде делятся цело на 4. На этом материал дизайн построен(хотя там даже 8, а не 4). Поэтому 48, 52, 56. Я б выбрал 56

2019-11-12 12:06 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/activity_detail.xml
> +        android:textSize="32dp"
шрифт задается sp

2019-11-12 12:06 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/activity_detail.xml
> +        android:paddingLeft="5dp"
4

2019-11-12 12:06 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/activity_detail.xml
> +        app:layout_constraintHorizontal_bias="0.5"
remove

2019-11-12 12:06 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/activity_recycler.xml
> +
extra line

2019-11-12 12:06 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/activity_recycler.xml
> +        tools:layout_editor_absoluteX="112dp"
tools:layout_editor_absolute remove

2019-11-12 12:06 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/list_item_view.xml
> +        android:id="@+id/recycler_image"
image_city

2019-11-12 12:06 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/list_item_view.xml
> +        android:layout_width="32dp"
Cтандартный размер каринок в элементе 40 на 40

2019-11-12 12:06 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/list_item_view.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Имхо лучше использовать констреинт. Хотя в данном случае и линеар сойдет

2019-11-12 12:06 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/list_item_view.xml
> +    android:layout_height="72dp"
Когда у тебя в элементе всего одна строка, то размер 56dp - в презенташке ж это было

2019-11-12 12:06 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/list_item_view.xml
> +
extra lines

2019-11-24 20:09 UTC, NailShaykhrazievItis approved these changes

2019-12-02 08:21 UTC, closed without merging