Task/home6
whiskas90/HomeWorkAndroid pull request #6
Opened 2019-11-09 22:28 UTC by whiskas90

home 6 add

2019-11-09 22:32 UTC, whiskas90 commented
![photo_2019-11-10_01-30-05](https://user-images.githubusercontent.com/42836742/68535842-d93f5300-0359-11ea-8d07-0a176d2389b4.jpg)
![photo_2019-11-10_01-30-05 (2)](https://user-images.githubusercontent.com/42836742/68535843-dba1ad00-0359-11ea-9217-3b058b19f206.jpg)
![photo_2019-11-10_01-30-06](https://user-images.githubusercontent.com/42836742/68535844-de040700-0359-11ea-82ff-18ee761fc6cb.jpg)
![photo_2019-11-10_01-30-06 (2)](https://user-images.githubusercontent.com/42836742/68535845-e0fef780-0359-11ea-95f6-1f45560db267.jpg)

При нажатии на add product снова перенаправляет на заполнение полей

2019-11-12 17:26 UTC, whiskas90 commented
Перед 7 домашкой я залью в мастер это изменение
 implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version", просто в этой дз я еще изменял версию

2019-12-07 16:19 UTC, NailShaykhrazievItis requested changes

2019-12-07 16:19 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/myandroidproject/DrawerActivity.kt
> +        supportFragmentManager.also {
supportFragmentManager.beginTransaction().apply {
везде поправишь

2019-12-07 16:19 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/myandroidproject/DrawerActivity.kt
> +        val navController = findNavController(R.id.nav_host_fragment)
А у тебя не конфликтуют навконтроллер и OnNavigationItemSelectedListener ? оч подозрительно

2019-12-07 16:19 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/myandroidproject/ui/add_info_about_product/AddInfoAboutProductFragment.kt
> +        private const val ARG = "sum"
ARG_SUM
везде поправишь

2019-12-07 16:19 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/myandroidproject/ui/add_product/AddProductFragment.kt
> +                    addToBackStack(null).commit()
addToBackStack(null)
commit()

2019-12-07 16:19 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/myandroidproject/ui/product/ProductFragment.kt
> +    ): View? {
View? = inflater.inflate(R.layout.fragment_product, container, false)

2019-12-07 16:19 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/myandroidproject/ui/show_product_info/ShowProductInfoFragment.kt
> +        private const val NAME = "prod_name"
ARG_NAME
ARG_TYPE
ARG_PRICE

2019-12-07 16:19 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/fragment_show_product_info.xml
> +        android:id="@+id/textView_show_product_name"
tv_show_product_name

2019-12-07 16:19 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/fragment_show_product_info.xml
> +        android:id="@+id/textView_show_product_type"
tv

2019-12-07 16:19 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/fragment_show_product_info.xml
> +        android:id="@+id/textView_show_product_price"
tv

2019-12-07 16:19 UTC, NailShaykhrazievItis commented on app/src/main/res/values-v21/styles.xml
> +    <style name="AppTheme.NoActionBar">
А зачем этот файл??? У тебя итак минимальная версия должна быть 21

2020-03-01 20:54 UTC, closed without merging